version: "3.9"
services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
      - MYSQL_PASSWORD=root
    restart: unless-stopped
    volumes:
      -  /home/mysql/data:/var/lib/mysql
    networks:
      - ci-net 

  spring-service:
    image: elmoatazbelleh/achat
    ports:
      - 8089:8089
    environment :
      -SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/achatdb
      -SPRING_DATASOURCE_USERNAME : root
      -SPRING_DATASOURCE_PASSWORD : root
    depends_on:
      - mysqldb
    restart: unless-stopped
    networks:
      - ci-net
networks:
  ci-net: