version: '3.3'

services:
    #service 1: definition of mysql database
    db:
      image: mysql/mysql-server:8.0
      container_name: mysql2   
      environment:
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_USER=root
      ports:
        - "3306:3306"
      restart: always
    
    #service 3: definition of your spring-boot app 
    customerservice:                       #it is just a name, which will be used only in this file.
      image: arwabejaoui/springprojet1               #name of the image after dockerfile executes
      container_name: pensive_bhaskara  #name of the container created from docker image
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
        - "8082:8082"                       #docker containter port with your os port
      restart: always
        
      depends_on:                           #define dependencies of this app
        - db                                #dependency name (which is defined with this name 'db' in this file earlier)
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql2:3306/customer?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: pass
