version: "3"
services:

  mysqldb:
    image: mysql:8
    volumes:
      -  /home/mysql/achatdata:/var/lib/mysql:rw
    networks:
      - net-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    restart:  on-failure

  spring-achat:
    image: elmoatazbelleh/achat:latest
    ports:
      - "8089:8089"
    networks:
      - net-mysql
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/achatdb
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysqldb
    restart:  on-failure
 

     
networks:
  net-mysql: 